name: Go Tests

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        go-version: ['1.19', '1.20']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go get ./...

    - name: Run tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...

    - name: Upload to codecov
      uses: codecov/codecov-action@v1.0.6
