name: Go Tests

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        go-version: ['1.14', '1.15', '1.16', '1.17', '1.18']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install dependencies
      run: go get ./...
    - name: Run tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
    - name: Upload to codecov
      uses: codecov/codecov-action@v1.0.6
